import React from "react";
import { shopInfo } from "../data/siteData";

export default function Terms() {
  const sections = [
    { title: "1. Booking & Appointments", content: `All bookings made through the ${shopInfo.name} website are subject to availability and confirmation. Once your booking is submitted, you will receive a confirmation. If you need to reschedule or cancel, please contact us at least 24 hours before your appointment.` },
    { title: "2. Cancellations & No-Shows", content: `We understand that life happens. If you need to cancel, please give us at least 24 hours' notice. Repeated no-shows or late cancellations may result in a fee or the requirement of a deposit for future bookings.` },
    { title: "3. Pricing & Payment", content: `All prices listed on the website are in South African Rand (ZAR) and subject to change without notice. Payment is due at the time of service. We accept cash, all major credit cards, and digital payments.` },
    { title: "4. Services", content: `Our services are performed by trained professionals. While we strive for perfection, results may vary based on hair type, length, and condition. If you are unsatisfied with your service, please let us know within 48 hours and we will do our best to make it right.` },
    { title: "5. Health & Safety", content: `For the safety of our staff and clients, please inform us of any skin conditions, allergies, or medical concerns before your service. We reserve the right to refuse service if we believe it may pose a health risk.` },
    { title: "6. Personal Information", content: `We collect personal information (name, email, phone number) solely for the purpose of managing your bookings and communicating with you about your appointments. We do not sell or share your information with third parties.` },
    { title: "7. Calendar Integration", content: `Our booking system allows you to add appointments to your personal calendar (Google Calendar, Apple Calendar, etc.). This feature is provided as a convenience. ${shopInfo.name} is not responsible for errors or omissions in calendar events generated by third-party platforms.` },
    { title: "8. Website Use", content: `By using this website, you agree to use it for lawful purposes only. You may not attempt to disrupt, hack, or misuse the website or its booking system.` },
    { title: "9. Limitation of Liability", content: `${shopInfo.name} is not liable for any indirect, incidental, or consequential damages arising from the use of our website or services. Our total liability is limited to the amount paid for the service in question.` },
    { title: "10. Changes to Terms", content: `We reserve the right to update these Terms & Conditions at any time. Changes will be effective immediately upon posting to the website. Continued use of the site constitutes acceptance of the updated terms.` },
    { title: "11. Contact", content: `If you have any questions about these Terms & Conditions, please contact us at ${shopInfo.email} or ${shopInfo.phone}.` },
  ];

  return (
    <section className="section-padding pt-32">
      <div className="container-wide max-w-3xl">
        <p className="font-script text-copper text-3xl mb-2">Legal</p>
        <h1 className="font-heading text-4xl md:text-6xl text-bone mb-4">Terms & Conditions</h1>
        <p className="text-bone/40 text-sm mb-12">Last updated: {new Date().toLocaleDateString("en-ZA", { year: "numeric", month: "long", day: "numeric" })}</p>
        <div className="space-y-10">
          {sections.map((section) => (
            <div key={section.title}>
              <h2 className="font-heading text-lg text-copper mb-3 tracking-wider">{section.title}</h2>
              <p className="text-bone/60 leading-relaxed text-sm">{section.content}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}